@Bloggit.API_HostAddress = https://localhost:7291

GET {{Bloggit.API_HostAddress}}/api/v1/Post
Accept: application/json

###

POST {{Bloggit.API_HostAddress}}/api/v1/Post
Content-Type: application/json
{
    "title": "My Second Post",
    "content": "This is the content of the post.",
    "author": 2
}